import type { CostLog } from "./cost.types";

export const SEEDED_COST_PROJECTS = [
  {
    id: "paris-brest-demo",
    title: "Paris-Brest praline cream",
    status: "review",
  },
  {
    id: "tarte-citron-reference-pass",
    title: "Tarte citron meringue texture pass",
    status: "references_ready",
  },
];

export const SEEDED_COST_LOGS: CostLog[] = [
  {
    id: "cost-paris-brest-segment-1",
    videoId: "paris-brest-demo",
    segmentId: "paris-brest-segment-1",
    provider: "runway",
    model: "seedance2",
    operation: "seedance_segment_generation_started",
    creditsUsed: 864,
    costDollars: null,
    tokensInput: null,
    tokensOutput: null,
    metadata: {
      estimated: true,
      segmentPosition: 1,
      segmentTitle: "Texture-first praline hook",
      segmentStatus: "accepted",
      generationStatus: "succeeded",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T18:10:00.000Z",
  },
  {
    id: "cost-paris-brest-segment-2",
    videoId: "paris-brest-demo",
    segmentId: "paris-brest-segment-2",
    provider: "runway",
    model: "seedance2",
    operation: "seedance_segment_generation_started",
    creditsUsed: 1_080,
    costDollars: null,
    tokensInput: null,
    tokensOutput: null,
    metadata: {
      estimated: true,
      segmentPosition: 2,
      segmentTitle: "Choux piping and bake",
      segmentStatus: "accepted",
      generationStatus: "succeeded",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T18:18:00.000Z",
  },
  {
    id: "cost-paris-brest-segment-3-rejected",
    videoId: "paris-brest-demo",
    segmentId: "paris-brest-segment-3",
    provider: "runway",
    model: "seedance2",
    operation: "seedance_segment_generation_started",
    creditsUsed: 720,
    costDollars: null,
    tokensInput: null,
    tokensOutput: null,
    metadata: {
      estimated: true,
      segmentPosition: 3,
      segmentTitle: "Praline cream fill attempt",
      segmentStatus: "rejected",
      generationStatus: "succeeded",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T18:24:00.000Z",
  },
  {
    id: "cost-paris-brest-reference",
    videoId: "paris-brest-demo",
    segmentId: null,
    provider: "runway",
    model: "gpt_image_2",
    operation: "reference_image_generated",
    creditsUsed: 120,
    costDollars: null,
    tokensInput: null,
    tokensOutput: null,
    metadata: {
      estimated: true,
      generationStatus: "failed",
      referenceRole: "cut choux texture",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T18:30:00.000Z",
  },
  {
    id: "cost-paris-brest-openai",
    videoId: "paris-brest-demo",
    segmentId: null,
    provider: "openai",
    model: "gpt-5.5-high",
    operation: "storyboard_generated",
    creditsUsed: null,
    costDollars: 1.82,
    tokensInput: 18_420,
    tokensOutput: 5_940,
    metadata: {
      estimated: true,
      phase: "storyboard",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T17:55:00.000Z",
  },
  {
    id: "cost-paris-brest-mux",
    videoId: "paris-brest-demo",
    segmentId: "paris-brest-segment-1",
    provider: "mux",
    model: "basic-on-demand",
    operation: "segment_playback_uploaded",
    creditsUsed: null,
    costDollars: 0.14,
    tokensInput: null,
    tokensOutput: null,
    metadata: {
      estimated: true,
      segmentPosition: 1,
      segmentTitle: "Texture-first praline hook",
    },
    createdBy: "user-yoann",
    createdAt: "2026-05-08T18:36:00.000Z",
  },
];
