-- Register the LicornOutroVideo asset in the library.
--
-- Motivation:
--   * Recipe2Video's last segment is now a standardized "Licorn celebration
--     outro" generated by Seedance with a fixed prompt template and a
--     canonical 3s reference video as motion ancre.
--   * Seedance 2 `text_to_video` accepts up to 3 video references via
--     `referenceVideos[]`; we expose exactly one global asset
--     (`LicornOutroVideo`) shared across every recipe.
--
-- This migration only inserts the `asset_library` row. The corresponding
-- `media_assets` row + Storage object are created idempotently by
-- `scripts/upload-outro-asset.ts` from the local MP4 mirrored in the
-- agent workspace at `assets/character/outro/LicornOutroVideo.mp4`. Until
-- that script runs, `media_asset_id` stays NULL and
-- `resolveSegmentSeedanceReferences` refuses to resolve the entry, which
-- gives the operator a precise error rather than a silent broken segment.

insert into public.asset_library (canonical_name, category, aliases, description, status)
values (
  'LicornOutroVideo',
  'character',
  array['LicornOutro', 'OutroVideo']::text[],
  'Canonical 3s motion reference for the standardized Licorn celebration outro segment. Seedance video reference (mp4); the static dish stays in the foreground while the unicorn explodes with joy and a vertical rainbow burst behind her.',
  'active'
)
on conflict (canonical_name) do update
  set
    category = excluded.category,
    aliases = excluded.aliases,
    description = excluded.description,
    status = excluded.status,
    updated_at = now();
